displayThisText (typeof 42)
displayThisText (typeof xfcghvjbk)
displayThisText (typeof "42,42")
displayThisText (typeof $)
displayThisText (typeof Symbol())
displayThisText (typeof [1,2,3] )
displayThisText (typeof 9854569n)
displayThisText (typeof false)